### ISSUE TITLE
Account migration

### ISSUE THREAD

**Issue by SoniEx2** [PlaidWeb/publ-site#29]
It should be possible to migrate off twitter to something else!

**Comment by fluffy-critter** [comment]
I'm not clear what "account" you're talking about here. Publ's site doesn't have any accounts on it, and Publ itself doesn't maintain accounts either, aside from the author's user permission file.

**Comment by SoniEx2** [comment]
well yeah that.

like if you have our twitter in your permissions then we should be able to migrate off that somehow?

**Comment by fluffy-critter** [comment]
The way to do that is to just like, make an access request from the new identity and then the site owner opts to grant you the permissions from there. Either way that's not relevant to this repository, which is specifically for the website at https://publ.plaidweb.site/ and not for Publ itself.

**Comment by SoniEx2** [comment]
oh oops we got here because we were trying to make a publ site and forgot there's another repo sorry >.<
