### ISSUE TITLE
support atom exclusive content out of the box

### ISSUE THREAD

**Issue by SoniEx2** [PlaidWeb/publ-site#41]
atom feeds can have exclusive content (this is an atom-only feature, this is not possible with rss).

it'd be neat if the publ-site template supported it by default. an atom-exclusive post would only show up in atom feeds and would not have a web presence.

**Comment by fluffy-critter** [comment]
That's not relevant to Publ's website. If you want to add this to your website, probably the easiest way would be to make a custom entry type that is excluded from your HTML templates and is presented without a relevant `<link>` in the feed.

Publ also does not have the functionality necessary to completely disable presenting an entry within a particular template, so if someone were to know the entry ID, they could still force rendering the page. This can be mitigated with `redirect-to` metadata.

If you'd like to propose an alternate approach to making a feed-only entry (such as providing a template allow/denylist for an entry), please propose it on Publ itself.

Regardless, the Publ-site templates are not meant to be used as anything other than a reference, outside of maintaining the actual website itself. At some point I do want to make a feature demo section, which would be a good place to showcase and provide implementation references, but that would still just be example code, not a turnkey implementation.
